### ISSUE TITLE
Ззигер, измени README.md

### ISSUE THREAD

**Issue by EclipseHub** [zziger/gamespacebot#1]
Вот на это: 

# WARNING!
Использование этого кода в полной мере или частично позволяется только на некоммерческих основаниях после разрешения автора.
Бот написан специально для сервера [GameSpace](https://discord.io/gspace) в [Discord](https://discord.gg).<br><br>
Репозиторий SpaceBot Moderator: [кликни на меня](https://github.com/zziger/gamespacemoderator)<br><br>
Copyright 2018 © [GameSpace](https://discord.io/gspace) (кликните на GameSpace, чтобы попасть на Discord сервер). Все права защищены.<br>
Нарушение авторских прав преследуется законом.<br><br>
CC-BY-NC-SA<br>
http://creativecommons.org/licenses/by-nc-sa/4.0/
# Благодарность
Огромное спасибо моему другу sqdEclipse, который помогал мне кодить этого бота.<br>
Discord: sqdEclipse#5372<br>
Site: https://vladciphersky.xyz (или же почта: [send@vladciphersky.xyz](mailto:send@vladciphersky.xyz))

**Comment by zziger** [comment]
Репозиторий закрыт, оставлен как архив. В скором времени будет удален.
